### ISSUE TITLE
PreRelease ToDo: Input function

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/mortAAR#16]
implement the option/"method-switcher" to state whether the age intervals are inclusive or exclusive, i.e. 20-39 and 40-60 vs. 20-40 and 40-60

**Comment by FFaupel** [comment]
Before closing this issue, Martin need to change the test, so that we can set "excluded" correctly as "default".

**Comment by nevrome** [comment]
The changes in 793bd21b150225bf6212e40fe7258e9f9ea9d6b4 [broke the vignette](https://travis-ci.org/ISAAKiel/mortAAR/builds/241176842). 

```
Quitting from lines 107-119 (mortAAR_vignette-1.Rmd) 
Error in while (sum(meth) < max(asd$ende)) { : 
  missing value where TRUE/FALSE needed
```

Pls fix. Btw. it's "method" not "methode".

**Comment by whamer** [comment]
Hey Clemens, I found the error; the example dataset did contain NA values in the columns "agebeg" and "ageend". I implemented some code to delete this rows. This was a problem of the function to deal with faulty input. Did we change the example dataset?

**Comment by nmueller18** [comment]
At the moment, when no group is specified the input function produces a further table beside "Bestattungen", called "NA". The error must be somewhere around line 113 in some of the loops but I could not spot it. Besides, "Bestattungen" should be changed to something neutral like "sample" and "Alter" to "age" for coherence.

**Comment by nevrome** [comment]
@whamer 

Ok thanks. No the example dataset didn't change. Hm... 

When building the vignette via `devtools::document()` I still get the message: 
```
Unknown Type: promise (5)
Unknown Type: promise (5)
```
I don't know where this is coming from, but I guess there's something fishy with the new code. Probably something about [lazy evaluation](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Promise-objects) that kind of works, but maybe in an unstable way... 

Could you please take a look at that?

**Comment by whamer** [comment]
Hey @nevrome , I read a bit about this lazy evaluation and do not see what our changes have to do with it. Perhaps you see the connection if I explain our changes. Thursday we created a new variable and gave it a default value. In the function we integrated an if-question. If the new variable is a specific character string (which is not the default value) the values of one column shoul be reduced by one. You see the function  should work as before. 
The error I found yesterday was, that there were NA values in the example dataset. The function was not able to deal with this NA values as it could not have been able to deal with this values before we edited the function on thursday. I fixed this problem by implementing some lines of code filtering the NA values out. Can the problem be that we worked in windows and only updated the parts we changed, and not all parts RStudio  said were changed?

**Comment by nevrome** [comment]
@whamer 

03da9bfd2a34213f705ba83edbd06ef513d3f7ae solved the issue. Still not sure what caused the problem, but eventually you were right: It was related to the dataset.

**Comment by nevrome** [comment]
The discussion in #20 brought to light, that `prep.life.table()` needs better documentation. It's especially important to describe the different types of input data the function manages to wrangle.

**Comment by FFaupel** [comment]
working on it...

**Comment by FFaupel** [comment]
added "documentation" and "examples" for input function
@nmueller18 we should check, if everything is documented correctly now...

**Comment by nmueller18** [comment]
@nevrome  Thanks for "tidying" the extended vignette. However, the mutate function throws an error "Fehler in mutate_impl(.data, dots) : Objekt 'age' nicht gefunden". Could you have a look at this?

**Comment by nmueller18** [comment]
@nevrome Solved the issue myself thanks to this [stackoverflow-question](https://stackoverflow.com/questions/38649533/case-when-in-mutate-pipe).

**Comment by MartinHinz** [comment]
Can we consider this issue as closed than?

**Comment by nmueller18** [comment]
Someone not involved in the input function should check if the documentation is sufficient now ...

**Comment by nevrome** [comment]
Concerning the case_when bug:

Interesting. Both versions work for me. Which version of dplyr are you using?

**Comment by MartinHinz** [comment]
Fine in general, at least I did understand it. Minor (?): argument "methode" is still german. We should change that, although it will mean some search and destroy in vignettes and tests.

**Comment by nmueller18** [comment]
@nevrome dplyr 0.5.0

**Comment by nevrome** [comment]
To second @MartinHinz, I suggest to rename the attributes "grnam" to "grname" and "age.range" to "agerange".

@nmueller18 I guess the old dplyr version was the problem.
